apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: varseldb-api
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{version}}
  port: 8080
  liveness:
    path: /varseldb-api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /varseldb-api/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /varseldb-api/internal/metrics
  replicas:
    min: 2
    max: 4
  ingresses:
    - "https://varseldb-api.dev.intern.nav.no/"
  vault:
    enabled: true
  azure:
    application:
      enabled: true
  webproxy: true
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "500m"
      memory: 580Mi
